export default function () {
  return {
    allClients:[
      {
        id: "12321",
        name:'John',
        clientSince:'2022-01-12',
        sex:'Male',
        age:'32',
        occupation:'Engineer',
        mobileNo:'09123456789',
        telNo:'1234567',
        address:'Earth',
        recentSchedule:'2022-02-06',
        procedure:'Crowns',
        diagnosis:'Crowning treatment',
      },
      {
        id: "2313",
        name:'Jane',
        clientSince:'2022-01-12',
        sex:'Female',
        age:'28',
        occupation:'Engineer',
        mobileNo:'09987654321',
        telNo:'4321765',
        address:'Mars',
        recentSchedule:'2021-12-25',
        procedure:'Teeth Cleaning',
        diagnosis:'Teeth treatment',
      }
    ],
    events: [
      {
        id: 1,
        name: "1st of the Month",
        procedure:
          "Everything is funny as long as it is happening to someone else",
        time: "All Day",
        date: "2022-02-01",
        bgcolor: "orange",
      },
      {
        id: 2,
        name: "Sisters Birthday",
        procedure: "Buy a nice present",
        time: "All Day",
        date: "2022-02-07",
        bgcolor: "green",
      },
      {
        id: 3,
        title: "Meeting",
        procedure: "Time to pitch my idea to the company",
        time: "10:00",
        date: "2022-02-10",
        bgcolor: "red",
      },
      {
        id: 4,
        name: "Lunch",
        procedure: "Company is paying!",
        time: "11:30",
        date: "2022-02-10",
        bgcolor: "teal",
      },
      {
        id: 5,
        name: "Visit mom",
        procedure: "Always a nice chat with mom",
        time: "17:00",
        date: "2022-02-20",
        bgcolor: "grey",
      },
      {
        id: 6,
        name: "Conference",
        procedure: "Teaching Javascript 101",
        time: "08:00",
        date: "2022-02-22",
        bgcolor: "blue",
      },
      {
        id: 7,
        name: "Girlfriend",
        procedure: "Meet GF for dinner at Swanky Restaurant",
        time: "19:00",
        date: "2022-02-22",
        bgcolor: "teal",
      },
      {
        id: 8,
        name: "Rowing",
        procedure: "Stay in shape!",
        time: "All Day",
        date: "2022-02-27",
        days: 2,
        bgcolor: "purple",
      },
      {
        id: 9,
        name: "Fishing",
        procedure: "Time for some weekend R&R",
        time: "All Day",
        date: "2022-02-27",
        days: 2,
        bgcolor: "purple",
      },
      {
        id: 10,
        name: "Vacation",
        procedure: "Trails and hikes, going camping! Don't forget to bring bear spray!",
        time: "All Day",
        date: "2022-02-29",
        days: 10,
        bgcolor: "purple",
      },
    ],
  } 
}
